[package]
name = "tokei_practice"
version = "0.1.0"
authors = ["minoring <minho1350@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tera = "1.5.0"

[dependencies]
log = "0.4.11"
clap = "2.33.3"
